###
# Add a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My First Post",
  "content": "This is the content of the first post.",
  "sender": "Noa"
}
###

GET http://localhost:3000/posts

###

# Get a post by ID
GET http://localhost:3000/posts/67443b63403364e20bdcb8ad

###

GET http://localhost:3000/sender?sender=Noa


###

# Update a post by ID
PUT http://localhost:3000/posts/67443b63403364e20bdcb8ad
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content for the post."
}

###
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "64b1f69b4f1a25673e18b521",
  "content": "This is a test comment.",
  "sender": "Yuvalben ",
  "createdAt": "2021-08-01T12:00:00.000Z"

}